### ISSUE TITLE
DS1.6 - Service filter

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-disruptions#13]
***

🗂 **Project ID:** DS1
📝 **Story No:** 6
🚩 **Priority:** M
***

**Epic:**
See disruption information that is relevant to me
***
<details>
<summary>Story details</summary>
<br/>

✏️ **Design Size:** 5
⌨️ **Dev Size:** 8

**Assigned to:**

***
#### As a
L/C/B

#### I need to
be able to filter disruption by by public transport service  (bus number, tram line, train journey) or road number

#### In order to
get information that is relevant to me

***

#### Acceptance criteria
Can I...?
- [ ] search for my bus number, metro line, train line (A to B)
- [ ] Can I see disruption updates just for that route on the map

</details>

***

**Comment by daylesalmon** [comment]
Related to: https://github.com/wmcadigital/wmn-disruptions-v2/issues/9

**Comment by benjaminthedev** [comment]
This is now completed and is #9 and push to master.
