### ISSUE TITLE
DS3.1B -  Add a favourite train journey/line (point A to B) to the home page widget

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-disruptions#131]
***

🗂 **Project ID:** DS3
📝 **Story No:** 1B
🚩 **Priority:** M
***

**Epic:**

***
<details>
<summary>Story details</summary>
<br/>

✏️ **Design Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️
⌨️ **Dev Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️

**Assigned to:**

***
#### As a
Leisure/Commuter/Business

#### I need to
be able to add a favourite train journey (point A to B) to display on the home page widget

#### In order to
get information that is directly relevant to my journey

***

#### Acceptance criteria
Can I...?
- [x] search for a train station start point and an end point?
- [x] I add this journey to a widget

</details>

***

**Comment by daylesalmon** [comment]
Went live via: https://github.com/wmcadigital/tfwm-travel-updates-widget/pull/10
