### ISSUE TITLE
DS3.2A - See my chosen buses on the homepage

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-disruptions#135]
***

🗂 **Project ID:** DS3
📝 **Story No:** 2A
🚩 **Priority:** M
***

**Epic:**

***
<details>
<summary>Story details</summary>
<br/>

✏️ **Design Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️
⌨️ **Dev Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️

**Assigned to:**

***
#### As a
Leisure/Commuter/Business

#### I need to
be able to see my chosen buses on the homepage

#### In order to
get information that is directly relevant to my journey
***

#### Acceptance criteria
Can I...?
- [x] see the bus  that I have chosen on the homepage? 

</details>

***

**Comment by daylesalmon** [comment]
Went live via: https://github.com/wmcadigital/tfwm-travel-updates-widget/pull/10
