### ISSUE TITLE
UI.3 Umbraco templates

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-disruptions#19]
***

🗂 **Project ID:** UI
📝 **Story No:** 3
🚩 **Priority:** M
***

**Epic:**
Integration
***
<details>
<summary>Story details</summary>
<br/>

✏️ **Design Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️
⌨️ **Dev Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️

**Assigned to:**

***
#### As a
Developer

#### I need to
create templates and doc types in Umbraco for disruptions page

#### In order to
integrate the disruptions app to go on the live website

***

#### Acceptance criteria
Can I...?
- [x] see disruptions app integrated into Umbraco?

</details>

***

**Comment by daylesalmon** [comment]
Closed via: https://github.com/wmcadigital/tfwm-travel-updates-widget/pull/10
