### ISSUE TITLE
UI5.2 - WMN UI components/patterns request (JotForm)

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-disruptions#20]
***

🗂 **Project ID:** UI5
📝 **Story No:** 2
🚩 **Priority:** M
***

**Epic:**

***
<details>
<summary>Story details</summary>
<br/>

✏️ **Design Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️
⌨️ **Dev Size:** 0/1/2/3/5/8/13/20/40/100/♾/❓/☕️

**Assigned to:**

***
#### As a
external digital team

#### I need to
be able to request new WMN UI components or patterns

#### In order to
implement products to support WMN app or website

***

#### Acceptance criteria
Can I...?
- [ ] access the request form?
- [ ] submit my request
- [ ] make WMCA design team aware of my request?

</details>

***

**Comment by daylesalmon** [comment]
@KaterinaKir @mrmjprice 

Closing as this in theory can be done via github issues for the design system: https://github.com/wmcadigital/wmn-design-system/issues/new/choose

Maybe we can update the templates for requesting a new component or something?
Raise this as an issue in design system repo.
