### ISSUE TITLE
UI4.1 - Feedback Loop - Tableau Dashboard

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-disruptions#21]
***

🗂 **Project ID:** UI4
📝 **Story No:** 1
🚩 **Priority:** S
***

**Epic:** Feedback loop for users to report if content is helpful

***
<details>
  <summary>Story details</summary>

***
✏️ **Design Size:** 2
⌨️ **Dev Size:** 8

**Assigned to:**

***

#### As a
C/L/B

#### I need
to be able to give feedback about pages/content

#### In order to
help content editors provide helpful content

***

#### Acceptance criteria
Can I...?
- [ ] rate a page as helpful/unhelpful?
- [ ] submit a comment if there is something wrong with the page?</details>

***

**Comment by sam-wmca** [comment]
@sudheer-rk this is paused for now
