### ISSUE TITLE
Styling Autocomplete

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-disruptions#218]
![IMG_1294](https://user-images.githubusercontent.com/57525718/77307630-85724c80-6cf1-11ea-83d7-c182d8485859.PNG)
Improve formatting of autocomplete options by increasing line length. Also investigate potential data issue for service A5 Wolverhampton to Unknown

**Comment by daylesalmon** [comment]
Smaller devices (less than 380px) now drop the route summary to a new line to give extra space for longer place names.

Bigger devices now have a wider space to put route names in to.

This will be closed automatically as part of the new build (due end of today).

@KaterinaKir 

![localhost_3000_](https://user-images.githubusercontent.com/13015201/77420019-3dbaf600-6dc1-11ea-8afe-7d9e83ed813c.png)
