### ISSUE TITLE
DS4.2 - Unsubscribe from email notifications for disruptions

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-disruptions#26]
***

🗂 **Project ID:** DS4
📝 **Story No:** 2
🚩 **Priority:** M
***

**Epic:** Sign up to and receive email notifications from disruptions on ICS

***
<details>
<summary>Story details</summary>
<br/>

✏️ **Design Size:** 5
⌨️ **Dev Size:** 3

**Assigned to:**

***
#### As a
L/C/B

#### I need to
be able to unsubscribe from email notifications

#### In order to
no longer receive updates about disruption

***

#### Acceptance criteria
Can I...?
- [x] unsubscribe from emails within a specific email

</details>

***

**Comment by daylesalmon** [comment]
Closing as this action can be done within the user's email management portal. Repo is located: https://github.com/wmcadigital/wmn-disruption-manage
