### ISSUE TITLE
Good service message on landing page (disruptions widget)

### ISSUE THREAD

**Issue by KaterinaKir** [wmcadigital/wmn-disruptions#406]
Show good service message on the landing page of disruptions widget if there are no disruptions.
Dynamic message should include time and mode. E.g good service today on all train lines or good service between [selected dates] as of today, but it is subject to change, check before you travel.

**Comment by gldgrnt** [comment]
@KaterinaKir I've updated a dynamic 'Good Service Message' locally in the following way:

"Good service ```{date}``` on/across all ```{mode}```."
"Service is subject to change, so please check before you travel." (if it's in the future)

**Examples:**

![image](https://user-images.githubusercontent.com/43111519/105019358-e9fb5680-5a3d-11eb-806b-c188a03d5cee.png)

![image](https://user-images.githubusercontent.com/43111519/105021211-321b7880-5a40-11eb-80ac-86c2a2ec027a.png)

![image](https://user-images.githubusercontent.com/43111519/105019896-8cb3d500-5a3e-11eb-859c-92529c1d4b50.png)

![image](https://user-images.githubusercontent.com/43111519/105020252-f8963d80-5a3e-11eb-93f5-fbcac8e64aa9.png)

Is this the kind of thing you were thinking?

**Comment by KaterinaKir** [comment]
Looks great. Thank you!
