### ISSUE TITLE
Mobile: Change height of the tray line to 3px and give it a border-radius of 3px.

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-disruptions#414]
The current tray line is too small on mobile and needs to be made bigger.

I'd suggest changing the height from 1px to 3px and adding a border-radius of 3px to smooth the edges. If there is a way to cap the edges of the line instead of using border-radius, then that would be even better.

Current design:
![Screenshot 2020-11-18 at 14 36 55](https://user-images.githubusercontent.com/62507489/99543819-84420e00-29ab-11eb-988a-4a9e15724903.png)

With the changes applied, It should look like this:
![Screenshot 2020-11-18 at 14 33 32](https://user-images.githubusercontent.com/62507489/99543401-0a118980-29ab-11eb-91a8-070db5de3844.png)

**Comment by gldgrnt** [comment]
Hey @jkmnch , what do you mean when you say:

> "If there is a way to cap the edges of the line instead of using border-radius, then that would be even better."

**Comment by jkmnch** [comment]
@gldgrnt It does sound a bit confusing now that I've re-read it! What I was trying to mean was if both ends could be rounded, so it's not just a straight line

For example:
![Screenshot 2021-01-06 at 11 55 58](https://user-images.githubusercontent.com/62507489/103766096-25e1f500-5016-11eb-9f08-8ae210e5da34.png)

Hopefully, that clears things up...

**Comment by gldgrnt** [comment]
@jkmnch perfecto! thanks 👍🏾
