### ISSUE TITLE
App crashing on iOS [video]

### ISSUE THREAD

**Issue by gldgrnt** [wmcadigital/wmn-disruptions#447]
**Description**
When on mobile, the app first refreshes and then crashes after repeated uses of the mobile tray. 

*Occurs on:*
- iOS: Safari, Chrome

*Tested on:*
- iOS: Safari, Chrome
- Android: Chrome

*Recording*

https://user-images.githubusercontent.com/43111519/103910205-76338280-50fc-11eb-8c45-96691dadc9ff.mp4

**Comment by Doodlepaul** [comment]
Unable to duplicate issue.
