### ISSUE TITLE
Top of the tray hides behind the map when a disruption is selected (video) iOS - Safari & Chrome browsers

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-disruptions#451]
### Bug:
When I select a disruption in the map, the tray expands but the top of the tray is hidden behind the map. I then have to swipe the disruption information section for the top of the tray to expand to the top of the screen and hide the map.

This happens on both Chrome and Safari browsers on my iPhone 11 (iOS 14.3).

https://user-images.githubusercontent.com/62507489/104438652-1f103080-5588-11eb-909e-90b29a2fdfc2.mov

**Comment by gldgrnt** [comment]
Hey @jkmnch what's the expected behaviour for this?

**Comment by jkmnch** [comment]
@gldgrnt I'm double-checking with Kat, I thought this was a bug but I think I'm wrong.

**Comment by jkmnch** [comment]
@gldgrnt Is there a way to design it so the user doesn't need to scroll twice to view more of the disruption info? Currently, a user needs to scroll once to make the map disappear and then swipe again to see more on the disruption info.

**Comment by gldgrnt** [comment]
@jkmnch I think i've fixed this in the newest update to the [deploy preview](https://deploy-preview-450--wmn-disruptions.netlify.app/). (You might need to view in incognito / refresh your cache)

**Comment by jkmnch** [comment]
@gldgrnt New behaviour looks much better! Me and Kat are happy with it to go live :)

Thanks!
