### ISSUE TITLE
Hide favouriting functionality

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-disruptions#457]
We need to hide this until we can do something with the data, for example showing it on the user's homepage.

We need to keep the code so we can easily un-hide it when we've got the homepage widget

- [ ] Hide "Save routes to your homepage by pressing the star icon" help message
- [ ] Hide "Press star icon to save service {serviceNumber} to your favourites" and subsequent service number and star
- [ ] Hide stars from under "Affected services" indicators
- [ ] Hide stars from after train line names
- [ ] And the same for trams

**Comment by gldgrnt** [comment]
Functionality to show favourites on homepage has now been added
