### ISSUE TITLE
Home link in breadcrumb reacts really slowly

### ISSUE THREAD

**Issue by somtmee** [wmcadigital/wmn-disruptions#568]
When I press 'home' in the breadcrumbs on the main Disruptions page there's a 1-2 second delay before it does anything. A user might think this is broken.

[https://disruptions.tfwm.org.uk/](https://disruptions.tfwm.org.uk/). 

It does this whether on list or map view.

Browser and Device details:
Chrome version 92.0
MacOS Catalina version 10.15.6

**Comment by sudheer-rk** [comment]
Tested and working fine now.
