### ISSUE TITLE
Update disruption sharing content to new brand

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-disruptions#579]
### **Twitter**
When a user shares a disruption via Twitter, we auto-populate a hashtag and a link. This needs updating as it uses an old hashtag and tags the old Twitter account.

New hashtag: #TfWMDisruption
Twitter account: @TransportForWM

![Screenshot 2021-09-07 at 11 10 42](https://user-images.githubusercontent.com/62507489/132328619-2e25fd6d-bbb6-430a-8e87-0b18d917eb2b.png)

###  **Facebook**
When a user shares a disruption via Facebook, we auto-populate the old hashtag. 

New hashtag: #TfWMDisruption

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/62507489/132334780-0e97ee48-b588-41dd-9b72-51e6eb4d09d7.jpeg)

### **Email**

We also auto-populate the email subject. This will need changing to "Shared from tfwm.org.uk"

![Screenshot 2021-09-07 at 11 19 50](https://user-images.githubusercontent.com/62507489/132329322-06201066-ce12-488b-92d4-e191809b2660.png)

**Comment by Doodlepaul** [comment]
Twitter still auto-populates the hashtag as 'WMNDisruption'.

![Screenshot 2022-08-15 at 15 07 17](https://user-images.githubusercontent.com/68856858/184651188-70f910b5-054e-4cc7-ba7c-5546ed0734c3.png)

**Comment by sam-wmca** [comment]
Facebook tested and fixed
