### ISSUE TITLE
Add bus timetable change email template into Campaign Monitor

### ISSUE THREAD

**Issue by jkmnch** [wmcadigital/wmn-disruptions#580]
We'll need to add a new disruption alert email template for bus timetable changes (issue #121).

I believe that the disruption emails were built in HTML first and uploaded into Campaign Monitor. I can upload the new HTML template myself.

Here is the Figma link to the new template: https://www.figma.com/file/zKPgvJmPW7Z5fc56wx7BHQ/Bus-Timetable-Disruption-Email?node-id=0%3A1

String properties
- Description holds bus service number
- StartTime holds timetable date
- Infoid holds the 'stateless' value to insert into the timetable URL

If you have any questions about the string properties, please ask Ian.

**Comment by jkmnch** [comment]
Issue moved to wmn-disruption-email-templates repo [#44](https://github.com/wmcadigital/wmn-disruption-email-templates/issues/44)

**Comment by sam-wmca** [comment]
This relates to a new feature, and has been paused for now.
