### ISSUE TITLE
Change header to title variant

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmn-disruptions#612]
The header needs to be changed to the [title variant](https://designsystem.tfwm.org.uk/patterns/header/).

Currently it is using a header that is not in the TfWM DS:

<img width="998" alt="image" src="https://user-images.githubusercontent.com/66072673/164233286-b376f594-b5c1-4c8c-a62b-102bb2f04ac8.png">

**Comment by sudheer-rk** [comment]
New header is provided by Mushtaque Ahmed 


![image](https://user-images.githubusercontent.com/92720228/183451186-2e1c23b6-4839-429e-ad31-be3dcf7d99ed.png)

**Comment by sam-wmca** [comment]
@sudheer-rk could you change this to the title variant please - https://designsystem.tfwm.org.uk/patterns/header/ 
<img width="676" alt="image" src="https://user-images.githubusercontent.com/66072673/183600375-fb5935f1-4106-42b2-8681-2794ab646e7a.png">

The text within the title header can be: **Find live and planned disruptions**
