### ISSUE TITLE
Update <title> tag

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmn-disruptions#613]
The <title> tag attribute is using the old brand name:
`<title>Disruptions - West Midlands Network</title>`

It should be:

`<title>Disruptions - Transport for West Midlands</title>`

**Comment by sudheer-rk** [comment]
@sam-wmca 
Description and short_name still says West Midlands Network. Do you want to update them?

"description": "Disruptions section of the West Midlands Network website",
 "short_name": "WMN Disruptions"
