### ISSUE TITLE
Update footer to TfWM DS component

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmn-disruptions#614]
The footer is using a non TfWM DS component:

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/66072673/164234233-abeb8f78-00a1-4d79-9e42-0b3aca58e0e5.png">

It should use the standard footer component, for example the one in [Find my Metro zones](https://find-metro-zones.tfwm.org.uk/).

The footer copyright and privacy policy link also need to be updated.

New copyright information: **© West Midlands Combined Authority [year]**

Privacy policy link: https://www.tfwm.org.uk/policies/privacy-and-cookies-policy/

**Comment by sudheer-rk** [comment]
New common header cdn link was provided by Mushtaque Ahmed. Screenshot is below


![image](https://user-images.githubusercontent.com/92720228/183449245-42eb22a4-072f-44ca-910f-588018c03e79.png)

**Comment by sam-wmca** [comment]
@sudheer-rk looking good, do you want me to close this ticket?
