### ISSUE TITLE
Fix feedback link in beta banner

### ISSUE THREAD

**Issue by sam-wmca** [wmcadigital/wmn-disruptions#615]
The feedback link in the banner is dead. The new link is https://forms.office.com/Pages/ResponsePage.aspx?id=RetZCK7xCk6e-ubWa7tnL1voVKMeFXVKvUhU3Uh8aqFUNUNVNFlKOVpLMThNV0g0T1VZWDYyT1FLNCQlQCN0PWcu

**Comment by sudheer-rk** [comment]
placed feedback link 'id' under environment variable section

**Comment by Doodlepaul** [comment]
Link is still going to dead hotjar survey...
